packages:
  - 'apps/*'
  - 'packages/*'

shamefullyHoist: true

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': set this to true or false
  bcrypt: true
  sharp: true
  unrs-resolver: set this to true or false
